name: Markdown Linting

on:
  push:
    paths:
      - '**/*.md'
  pull_request:
    paths:
      - '**/*.md'

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Updated to use Node.js 16
    - name: Install dependencies
      run: npm install -g markdownlint-cli@0.31.1  # Specify a version known to work
    - name: Run Markdown Linting
      run: markdownlint '**/*.md' --ignore node_modules